Fixed create env rhosp bmc
Change-Id: Ica9034137e8da45112a58e7575f3f0cf3c9acd15

diff --git a/jobs/devstack/rhosp/definitions b/jobs/devstack/rhosp/definitions
--- a/jobs/devstack/rhosp/definitions
+++ b/jobs/devstack/rhosp/definitions
@@ -17,7 +17,12 @@ declare -A RHOSP_PROVIDERS=( \
   ['vexxhost']='vexx' \
   ['vexx']='vexx' \
   ['bmc']='bmc' \
-  ['kvm']='kvm' \
+  ['openlab1']='bmc' \
 )
 
 export PROVIDER="${RHOSP_PROVIDERS[$CLOUD]}"
+
+[ -z "$PROVIDER" ] || {
+  echo "ERROR: unsupported provider for CLOUD=$CLOUD"
+  exit 1
+}
