update cleaning for docker in fetch job

diff --git a/jjb/jobs/fetch-sources.yaml b/jjb/jobs/fetch-sources.yaml
--- a/jjb/jobs/fetch-sources.yaml
+++ b/jjb/jobs/fetch-sources.yaml
@@ -78,10 +78,6 @@
           set -o pipefail
           source "$WORKSPACE/global.env"
           ./src/progmaticlab/tf-jenkins/infra/gerrit/apply_patchsets.sh ./src tungstenfabric/tf-dev-env ./patchsets-info.json
-          # special case for fetch-sources - if we have changes in tf-dev-env then we should rebuild it
-          if grep -q "tungstenfabric/tf-dev-env" ./patchsets-info.json ; then
-            echo "export DEVENVTAG=sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX" >> global.env
-          fi
       - shell: |
           source "$WORKSPACE/global.env"
           desc="Pipeline: ${PIPELINE_NAME}-${PIPELINE_NUMBER}  Random: ${JOB_RND}<br>Job logs: <a href=\"${LOGS_URL}/${STREAM}\">${LOGS_URL}/${STREAM}</a>"
@@ -96,6 +92,20 @@
           # do it as a latest source to override all exports
           source "${WORKSPACE}/vars.${JOB_NAME}.${JOB_RND}.env" || /bin/true
           export FULL_LOGS_PATH="${LOGS_PATH}/${STREAM}"
+
+          # definitions ONLY for this job
+          export TF_DEVENV_CONTAINER_NAME="tf-developer-sandbox-${PIPELINE_BUILD_TAG}${TAG_SUFFIX}"
+          # special case for fetch-sources - if we have changes in tf-dev-env then we should rebuild it
+          if grep -q "tungstenfabric/tf-dev-env" ./patchsets-info.json ; then
+            export DEVENVTAG=sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX
+            if docker images -a | grep $TF_DEVENV_CONTAINER_NAME ; then
+              IMAGES_TO_DELETE="$(docker image inspect "$TF_DEVENV_CONTAINER_NAME" --format {{.RepoTags}} | tr -d '[]')"
+              if [[ -n "$IMAGES_TO_DELETE" ]]; then
+                docker rmi $IMAGES_TO_DELETE
+              fi
+            fi
+          fi
+
           # main run
           ./src/progmaticlab/tf-jenkins/jobs/fetch/run.sh |& tee ${WORKSPACE}/output.log || res=1
           # collect logs
@@ -120,32 +130,39 @@
                         source "${WORKSPACE}/deps.${JOB_NAME}.${JOB_RND}.env" || /bin/true
                         # do it as a latest source to override all exports
                         source "${WORKSPACE}/vars.${JOB_NAME}.${JOB_RND}.env" || /bin/true
-                        # have cleanup here for case of 'cancel job'
-                        if [[ -e $WORKSPACE/stackrc.$JOB_NAME.env ]] ; then
-                            # cleanup only if worker was created
-                            source "$WORKSPACE/stackrc.$JOB_NAME.env"
-                            echo "INFO: cleanup workers"
-                            ./src/progmaticlab/tf-jenkins/infra/${SLAVE}/remove_workers.sh || true
-                            rm -f $WORKSPACE/stackrc.$JOB_NAME.env
-                        else
-                            echo "INFO: there is no env file. skipping workers cleanup"
-                        fi
-                        # docker cleanup
-                        CONTAINER="tf-developer-sandbox-${PIPELINE_BUILD_TAG}${TAG_SUFFIX}"
-                        if docker ps -a --format '{{.Names}}' | grep "$CONTAINER" ; then 
-                            if [[ "$(docker container inspect $CONTAINER --format='{{ .State.Status }}')" == 'running' ]] ; then
-                                docker stop $CONTAINER
-                                docker rm $CONTAINER
-                            else
-                                docker rm $CONTAINER
-                            fi
+
+                        # definitions ONLY for this job
+                        export TF_DEVENV_CONTAINER_NAME="tf-developer-sandbox-${PIPELINE_BUILD_TAG}${TAG_SUFFIX}"
+                        # special case for fetch-sources - if we have changes in tf-dev-env then we should rebuild it
+                        if grep -q "tungstenfabric/tf-dev-env" ./patchsets-info.json ; then
+                          export DEVENVTAG=sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX
                         fi
 
-                        if docker images -a | grep "tf-developer-sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX" ; then
-                            IMAGES_TO_DELETE="$(docker image inspect "tf-developer-sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX" --format {{.RepoTags}} | tr -d '[]')"
-                            if [[ -n "$IMAGES_TO_DELETE" ]]; then
-                                docker rmi $IMAGES_TO_DELETE
-                            fi
+                        # have to cleanup here for case of 'cancel job'
+                        if [[ -e $WORKSPACE/stackrc.$JOB_NAME.env ]] ; then
+                          # cleanup only if worker was created
+                          source "$WORKSPACE/stackrc.$JOB_NAME.env"
+                          echo "INFO: cleanup workers"
+                          ./src/progmaticlab/tf-jenkins/infra/${SLAVE}/remove_workers.sh || true
+                          rm -f $WORKSPACE/stackrc.$JOB_NAME.env
+                        else
+                          echo "INFO: there is no env file. skipping workers cleanup"
                         fi
+
+                        # docker cleanup
+                        if docker ps -a --format '{{.Names}}' | grep "$TF_DEVENV_CONTAINER_NAME" ; then 
+                          if [[ "$(docker container inspect $TF_DEVENV_CONTAINER_NAME --format='{{ .State.Status }}')" == 'running' ]] ; then
+                            docker stop $TF_DEVENV_CONTAINER_NAME
+                          fi
+                          docker rm $TF_DEVENV_CONTAINER_NAME
+                        fi
+                        for name in "tf-developer-sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX" $TF_DEVENV_CONTAINER_NAME ; do
+                          if docker images -a | grep $name ; then
+                            IMAGES_TO_DELETE="$(docker image inspect "$name" --format {{.RepoTags}} | tr -d '[]')"
+                            if [[ -n "$IMAGES_TO_DELETE" ]]; then
+                              docker rmi $IMAGES_TO_DELETE
+                            fi
+                          fi
+                        done
         - archive:
             artifacts: '*.env'
