Fix cleanup worker for rhel

diff --git a/jjb/jobs/fetch-sources.yaml b/jjb/jobs/fetch-sources.yaml
--- a/jjb/jobs/fetch-sources.yaml
+++ b/jjb/jobs/fetch-sources.yaml
@@ -100,10 +100,11 @@
                     - shell: |
                         export DEBUG=true
                         source "$WORKSPACE/global.env"
+                        # have cleanup here for case of 'cancel job'
                         if [[ -e $WORKSPACE/stackrc.$JOB_NAME.env ]] ; then
-                            # cleanup only if worker was created
+                            # cleanup only if worker was created 
                             echo "INFO: cleanup workers"
-                            ./src/progmaticlab/tf-jenkins/infra/${SLAVE}/remove_workers.sh
+                            ./src/progmaticlab/tf-jenkins/infra/${SLAVE}/remove_workers.sh || true
                         else
                             echo "INFO: there is no file $WORKSPACE/stackrc.$JOB_NAME.env.. skip workers cleanup"
                         fi
