Rework docker cleanup

diff --git a/jjb/jobs/fetch-sources.yaml b/jjb/jobs/fetch-sources.yaml
--- a/jjb/jobs/fetch-sources.yaml
+++ b/jjb/jobs/fetch-sources.yaml
@@ -110,6 +110,7 @@
                     - UNSTABLE
                 build-steps:
                     - shell: |
+                        set -o pipefail
                         source "$WORKSPACE/global.env"
                         source "${WORKSPACE}/deps.${JOB_NAME}.${JOB_RND}.env" || /bin/true
                         # do it as a latest source to override all exports
@@ -124,10 +125,22 @@
                         else
                             echo "INFO: there is no env file. skipping workers cleanup"
                         fi
-                        CONTAINER="$(docker ps --all --quiet --filter 'status=running' --filter "name=tf-developer-sandbox-${PIPELINE_BUILD_TAG}${TAG_SUFFIX}")"
-                        if [[ -n "$CONTAINER" ]]; then
-                            docker stop $CONTAINER
-                            docker rm $CONTAINER
+                        # docker cleanup
+                        CONTAINER="tf-developer-sandbox-${PIPELINE_BUILD_TAG}${TAG_SUFFIX}"
+                        if docker ps -a --format '{{.Names}}' | grep "$CONTAINER" ; then 
+                            if [[ "$(docker container inspect $CONTAINER --format='{{ .State.Status }}')" == 'running' ]] ; then
+                                docker stop $CONTAINER
+                                docker rm $CONTAINER
+                            else
+                                docker rm $CONTAINER
+                            fi
+                        fi
+
+                        if docker images -a | grep "tf-developer-sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX" ; then
+                            IMAGES_TO_DELETE="$(docker image inspect "tf-developer-sandbox-$CONTRAIL_CONTAINER_TAG$TAG_SUFFIX" --format {{.RepoTags}} | tr -d '[]')"
+                            if [[ -n "$IMAGES_TO_DELETE" ]]; then
+                                docker rmi $IMAGES_TO_DELETE
+                            fi
                         fi
         - archive:
             artifacts: '*.env'
